name: Build & Test .NET Backend

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet restore ./src/Biblioteca.Api/Biblioteca.Api.csproj
      - run: dotnet build ./src/Biblioteca.Api/Biblioteca.Api.csproj -c Release --no-restore
      - run: dotnet test ./tests/Biblioteca.Tests/Biblioteca.Tests.csproj --no-build
      - run: dotnet publish ./src/Biblioteca.Api/Biblioteca.Api.csproj -c Release -o ./publish
      - uses: actions/upload-artifact@v4
        with:
          name: biblioteca-api
          path: ./publish
